version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-test-link:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Kill any remaining processes
          command: kill $(lsof -t -i:3001) || true

  my-workflow:
    jobs:
      - build-test-link
